name: 'Octometrics Action'
description:
  'Use octometrics to monitor detailed profiling information about your GitHub
  Actions workflows'
author: 'Adam Hamrick'

inputs:
  version:
    description:
      'Version of octometrics to install (e.g. v1.0.0). If not specified, latest
      release will be used.'
    default: 'latest'
    required: false
  interval:
    description:
      'Go duration string for how often to poll for profiling information'
    default: '1s'
    required: false

outputs:
  version:
    description: 'The version of octometrics that was installed'
  path:
    description: 'The path to the installed octometrics binary'

runs:
  using: 'node20'
  main: 'dist/main.js'
  post: 'dist/post.js'

branding:
  icon: 'download'
  color: 'blue'
