name: octometrics-action
description: Record metrics from your GitHub Actions
author: kalverra

inputs:
  version:
    description: Specify the version of octometrics to use
    required: false
    default: latest

runs:
  using: node20
  main: dist/main.js
  post: dist/post.js
