name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Test Octometrics Action
        uses: ./
        with:
          job_name: Integration Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Simulate CPU Usage
        id: simulate-cpu-usage
        run: |
          echo "Simulating CPU usage..."
          for i in {1..100}; do
            echo "Simulating CPU usage - iteration $i"
            for j in {1..10000}; do
              num1=$((RANDOM % 1000))
              num2=$((RANDOM % 1000))
              sum=$((num1 + num2))
            done
          done

      - name: Simulate Memory Usage
        id: simulate-memory-usage
        run: |
          echo "Simulating memory usage..."
          # Create an array and continuously append data to it
          declare -a memory_array
          for i in {1..2}; do
            echo "Simulating memory usage - iteration $i"
            # Generate a 10MB string and store it in the array
            for j in {1..1024}; do
              memory_array+=("$(head -c 10240 /dev/urandom | base64)")
            done
          done
          # Clear the array to free memory
          unset memory_array

      - name: Simulate Disk Usage
        id: simulate-disk-usage
        run: |
          echo "Simulating disk usage..."
          # Create a directory for disk usage simulation
          mkdir -p disk_test
          cd disk_test

          for i in {1..10}; do
            echo "Simulating disk usage - iteration $i"
            # Create a 50MB file with random data
            dd if=/dev/urandom of="test_file_$i" bs=1M count=50
            # Read the file to simulate disk read operations
            cat "test_file_$i" > /dev/null
          done

          # Clean up the test files
          cd ..
          rm -rf disk_test

      - name: Simulate Network Usage
        id: simulate-network-usage
        run: |
          echo "Simulating network usage..."
          for i in {1..10}; do
            echo "Simulating network usage - iteration $i"
            # Download a webpage and measure the time taken
            curl -o /dev/null -s -w "Download time: %{time_total}s\n" "https://google.com"
          done
